"""
Durable meme storage (Growth Phase B). save_meme() writes image bytes
(PNG by default, GIF for Growth Phase G's animated templates) to
Cloudflare R2 when creds are configured, falling back to the local
static/generated/ directory (today's pre-Phase-B behavior) when they're
not. Local storage is the fully-functional default, not a degraded mode
— every test in this repo runs against it with zero new env vars set.

delete_memes() is the matching removal, used when a user deletes a
conversation or asks to be forgotten.
"""

from __future__ import annotations

import asyncio
import secrets
import string
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import boto3

from config import Settings, get_settings

BACKEND_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BACKEND_ROOT / "static" / "generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

_BASE62_ALPHABET = string.digits + string.ascii_letters


@dataclass
class SavedMeme:
    meme_id: str
    url: str
    path: Path | None  # set for local storage; None when stored remotely (R2)


def generate_meme_id() -> str:
    """Unguessable — secrets.choice (CSPRNG), not random, per the growth
    spec's explicit requirement. Base62, 10 chars: 62**10 ≈ 8.4e17
    possibilities. This id is used as the storage object key, the PNG
    provenance tEXt value, and the Postgres memes.id primary key — one id,
    three uses."""
    return "".join(secrets.choice(_BASE62_ALPHABET) for _ in range(10))


def _r2_configured(settings: Settings) -> bool:
    return bool(
        settings.r2_account_id
        and settings.r2_access_key_id
        and settings.r2_secret_access_key
        and settings.r2_bucket
        and settings.r2_public_base_url
    )


@lru_cache(maxsize=4)
def _cached_r2_client(account_id: str, access_key_id: str, secret_access_key: str):
    """boto3.client() construction is real, avoidable overhead on every
    call (it loads the S3 service model) — on Render's 512MB free tier,
    already dominated by ChromaDB's embedding model at baseline, doing
    this on every single meme save is exactly the kind of avoidable
    per-request cost that tips a tight ceiling over. Cached by the actual
    credential values (not the whole Settings object, which isn't stably
    hashable) — production has one fixed set of creds so this caches once
    for the process lifetime; a genuine credential rotation would need a
    process restart to pick up, which redeploys already do."""
    return boto3.client(
        "s3",
        endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=access_key_id,
        aws_secret_access_key=secret_access_key,
    )


def _r2_client(settings: Settings):
    return _cached_r2_client(
        settings.r2_account_id, settings.r2_access_key_id, settings.r2_secret_access_key
    )


async def save_meme(
    data: bytes,
    meme_id: str | None = None,
    extension: str = "png",
    content_type: str = "image/png",
) -> SavedMeme:
    """The only place a generated meme's bytes get persisted. Picks R2 or
    local disk based on whether R2 creds are fully configured — never a
    silent partial fallback if creds are present but something's
    misconfigured; a save failure raises rather than quietly losing
    durability.

    `meme_id` is normally pre-generated by the caller (compositor.py needs
    it before the save, to embed in the PNG's provenance tEXt chunk) —
    generated here only if the caller doesn't care and omits it.

    `extension`/`content_type` default to today's PNG-only behavior —
    Growth Phase G's GIF templates are the first caller to pass
    extension="gif"/content_type="image/gif"; every other caller is
    unaffected."""
    settings = get_settings()
    if meme_id is None:
        meme_id = generate_meme_id()

    if _r2_configured(settings):
        client = _r2_client(settings)
        await asyncio.to_thread(
            client.put_object,
            Bucket=settings.r2_bucket,
            Key=f"{meme_id}.{extension}",
            Body=data,
            ContentType=content_type,
        )
        url = f"{settings.r2_public_base_url.rstrip('/')}/{meme_id}.{extension}"
        return SavedMeme(meme_id=meme_id, url=url, path=None)

    path = OUTPUT_DIR / f"{meme_id}.{extension}"
    path.write_bytes(data)
    return SavedMeme(meme_id=meme_id, url=f"/static/generated/{meme_id}.{extension}", path=path)


class MemeDeleteError(RuntimeError):
    """A stored meme image could not be removed. Raised, never swallowed:
    a caller deleting on a user's behalf has to be able to tell them."""


_LOCAL_URL_PREFIX = "/static/generated/"
_KNOWN_EXTENSIONS = ("png", "gif")
_R2_DELETE_BATCH = 1000  # the S3 API's limit for one DeleteObjects call


def _object_name(meme_id: str, url: str) -> str:
    """The name save_meme() stored this meme under. Built from the meme id
    and a known extension only — the url is read for its extension and for
    nothing else, so a bad url value can never aim a delete at another
    object."""
    extension = url.rsplit(".", 1)[-1].lower() if "." in url else ""
    if extension not in _KNOWN_EXTENSIONS:
        extension = "png"
    return f"{meme_id}.{extension}"


async def delete_memes(memes: list[tuple[str, str]]) -> None:
    """Remove the stored image for each (meme_id, url). Until this existed
    nothing ever deleted an image: removing a meme's database row left the
    file reachable at its url indefinitely.

    Safe to repeat — an image that is already gone is not an error, so a
    caller can retry after a partial failure. Anything that could not be
    removed raises MemeDeleteError."""
    if not memes:
        return
    settings = get_settings()

    local = [(meme_id, url) for meme_id, url in memes if url.startswith(_LOCAL_URL_PREFIX)]
    remote = [(meme_id, url) for meme_id, url in memes if not url.startswith(_LOCAL_URL_PREFIX)]

    for meme_id, url in local:
        (OUTPUT_DIR / _object_name(meme_id, url)).unlink(missing_ok=True)

    if not remote:
        return
    if not _r2_configured(settings):
        raise MemeDeleteError(
            f"{len(remote)} stored image(s) are in remote storage, which is not configured here"
        )

    client = _r2_client(settings)
    keys = [_object_name(meme_id, url) for meme_id, url in remote]
    failed = 0
    for start in range(0, len(keys), _R2_DELETE_BATCH):
        batch = keys[start : start + _R2_DELETE_BATCH]
        response = await asyncio.to_thread(
            client.delete_objects,
            Bucket=settings.r2_bucket,
            Delete={"Objects": [{"Key": key} for key in batch], "Quiet": True},
        )
        failed += len((response or {}).get("Errors") or [])
    if failed:
        raise MemeDeleteError(f"{failed} stored image(s) could not be removed")
