"""
Durable meme storage (Growth Phase B). save_meme() writes PNG bytes to
Cloudflare R2 when creds are configured, falling back to the local
static/generated/ directory (today's pre-Phase-B behavior) when they're
not. Local storage is the fully-functional default, not a degraded mode
— every test in this repo runs against it with zero new env vars set.
"""

from __future__ import annotations

import asyncio
import secrets
import string
from dataclasses import dataclass
from pathlib import Path

import boto3

from config import Settings, get_settings

BACKEND_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BACKEND_ROOT / "static" / "generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

_BASE62_ALPHABET = string.digits + string.ascii_letters


@dataclass
class SavedMeme:
    meme_id: str
    url: str
    path: Path | None  # set for local storage; None when stored remotely (R2)


def generate_meme_id() -> str:
    """Unguessable — secrets.choice (CSPRNG), not random, per the growth
    spec's explicit requirement. Base62, 10 chars: 62**10 ≈ 8.4e17
    possibilities. This id is used as the storage object key, the PNG
    provenance tEXt value, and the Postgres memes.id primary key — one id,
    three uses."""
    return "".join(secrets.choice(_BASE62_ALPHABET) for _ in range(10))


def _r2_configured(settings: Settings) -> bool:
    return bool(
        settings.r2_account_id
        and settings.r2_access_key_id
        and settings.r2_secret_access_key
        and settings.r2_bucket
        and settings.r2_public_base_url
    )


def _r2_client(settings: Settings):
    """Not cached — settings can change between calls in tests (monkeypatch),
    and constructing a boto3 client is cheap enough at this traffic volume
    that caching isn't worth the staleness risk."""
    return boto3.client(
        "s3",
        endpoint_url=f"https://{settings.r2_account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=settings.r2_access_key_id,
        aws_secret_access_key=settings.r2_secret_access_key,
    )


async def save_meme(png_bytes: bytes, meme_id: str | None = None) -> SavedMeme:
    """The only place a generated meme's bytes get persisted. Picks R2 or
    local disk based on whether R2 creds are fully configured — never a
    silent partial fallback if creds are present but something's
    misconfigured; a save failure raises rather than quietly losing
    durability.

    `meme_id` is normally pre-generated by the caller (compositor.py needs
    it before the save, to embed in the PNG's provenance tEXt chunk) —
    generated here only if the caller doesn't care and omits it."""
    settings = get_settings()
    if meme_id is None:
        meme_id = generate_meme_id()

    if _r2_configured(settings):
        client = _r2_client(settings)
        await asyncio.to_thread(
            client.put_object,
            Bucket=settings.r2_bucket,
            Key=f"{meme_id}.png",
            Body=png_bytes,
            ContentType="image/png",
        )
        url = f"{settings.r2_public_base_url.rstrip('/')}/{meme_id}.png"
        return SavedMeme(meme_id=meme_id, url=url, path=None)

    path = OUTPUT_DIR / f"{meme_id}.png"
    path.write_bytes(png_bytes)
    return SavedMeme(meme_id=meme_id, url=f"/static/generated/{meme_id}.png", path=path)
